sudo: required
services:
    - docker
before_install:
    - docker build -t dezarr/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true dezarr/react-test yarn test 
after_success:
    - docker build -t dezarr/multi-client ./client
    - docker build -t dezarr/multi-nginx ./nginx
    - docker build -t dezarr/multi-server ./server
    - docker build -t dezarr/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push dezarr/multi-client
    - docker push dezarr/multi-nginx
    - docker push dezarr/multi-server
    - docker push dezarr/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-2-296383875154"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY