sudo: required
services:
    - docker
before_install:
    - docker build -t dskochubey/react-test -f Dockerfile.dev .
script:
    - docker run -e CI=true dskochubey/react-test yarn test 
after_success:
    - docker build -t dskochubey/multi-client ./client
    - docker build -t dskochubey/multi-nginx ./nginx
    - docker build -t dskochubey/multi-server ./server
    - docker build -t dskochubey/multi-worker ./worker